### ISSUE TITLE
Provide a live example

### ISSUE THREAD

**Issue by jamesxv7** [TheGameFreak720/Albizu-Campos-Tribute-Page#1]
It would be nice to have a link with website. You can use a free hosting provider nothing fancy.

**Comment by TheGameFreak720** [comment]
Thanks for this suggestion. I will do it right away.

**Comment by jamesxv7** [comment]
One of the most rewarding things is watching the work online. Éxito!

**Comment by TheGameFreak720** [comment]
It is. Thanks :)

**Comment by jamesxv7** [comment]
One service that you can use is [Glitch](https://glitch.com). 
[Preview](https://fancy-bubble.glitch.me/)
[Files](https://glitch.com/edit/#!/fancy-bubble)

**Comment by TheGameFreak720** [comment]
Thanks for this. I was looking for a while for a page to showcase my test websites.
